/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_EVENTBASE_PB_H_INCLUDED
#define PB_EVENTBASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _EventBase {
    pb_callback_t id;
    pb_callback_t correlationId;
    int32_t deviceTime;
    pb_callback_t deviceId;
    int32_t version;
    pb_callback_t commandId;
    pb_callback_t payload;
/* @@protoc_insertion_point(struct:EventBase) */
} EventBase;


/* Initializer values for message structs */
#define EventBase_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define EventBase_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define EventBase_id_tag                         1
#define EventBase_correlationId_tag              2
#define EventBase_deviceTime_tag                 3
#define EventBase_deviceId_tag                   4
#define EventBase_version_tag                    5
#define EventBase_commandId_tag                  6
#define EventBase_payload_tag                    7

/* Struct field encoding specification for nanopb */
#define EventBase_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING, id, 1) \
X(a, CALLBACK, SINGULAR, STRING, correlationId, 2) \
X(a, STATIC, SINGULAR, INT32, deviceTime, 3) \
X(a, CALLBACK, SINGULAR, STRING, deviceId, 4) \
X(a, STATIC, SINGULAR, INT32, version, 5) \
X(a, CALLBACK, SINGULAR, STRING, commandId, 6) \
X(a, CALLBACK, SINGULAR, BYTES, payload, 7)
#define EventBase_CALLBACK pb_default_field_callback
#define EventBase_DEFAULT NULL

extern const pb_msgdesc_t EventBase_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EventBase_fields &EventBase_msg

/* Maximum encoded size of messages (where known) */
/* EventBase_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
