/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_LIGHTCONTROL_PB_H_INCLUDED
#define PB_LIGHTCONTROL_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LightControl {
    int32_t control;
/* @@protoc_insertion_point(struct:LightControl) */
} LightControl;


/* Initializer values for message structs */
#define LightControl_init_default                {0}
#define LightControl_init_zero                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define LightControl_control_tag                 1

/* Struct field encoding specification for nanopb */
#define LightControl_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, INT32, control, 1)
#define LightControl_CALLBACK NULL
#define LightControl_DEFAULT NULL

extern const pb_msgdesc_t LightControl_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LightControl_fields &LightControl_msg

/* Maximum encoded size of messages (where known) */
#define LightControl_size                        11

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
