/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_NEO_PROTO_PB_H_INCLUDED
#define PB_NEO_PROTO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _NEO_PROTO {
    int32_t deviceTime;
    int32_t version;
    float distance;
    float temperature;
    float humidity;
/* @@protoc_insertion_point(struct:NEO_PROTO) */
} NEO_PROTO;


/* Initializer values for message structs */
#define NEO_PROTO_init_default                   {0, 0, 0, 0, 0}
#define NEO_PROTO_init_zero                      {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define NEO_PROTO_deviceTime_tag                 1
#define NEO_PROTO_version_tag                    2
#define NEO_PROTO_distance_tag                   3
#define NEO_PROTO_temperature_tag                4
#define NEO_PROTO_humidity_tag                   5

/* Struct field encoding specification for nanopb */
#define NEO_PROTO_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, INT32, deviceTime, 1) \
X(a, STATIC, SINGULAR, INT32, version, 2) \
X(a, STATIC, SINGULAR, FLOAT, distance, 3) \
X(a, STATIC, SINGULAR, FLOAT, temperature, 4) \
X(a, STATIC, SINGULAR, FLOAT, humidity, 5)
#define NEO_PROTO_CALLBACK NULL
#define NEO_PROTO_DEFAULT NULL

extern const pb_msgdesc_t NEO_PROTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define NEO_PROTO_fields &NEO_PROTO_msg

/* Maximum encoded size of messages (where known) */
#define NEO_PROTO_size                           37

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
